### ISSUE TITLE
Баланс

### ISSUE THREAD

**Issue by Sarov991** [iWuna/Fallout-13-NewDecade#15]
-На время убрать Анклав (иск. Ивенты)
-Добавить наушник для НКР
-Увеличить количество обойм на М1 на базе НКР
-Сделать нормальную базу НКР
-Добавить в память имена всех бойцов НКР, дабы понимать: Один ты или нет.
-Я был-бы рад погонам капрала (Е-4) у обычной пехоты
Это всё.

**Comment by SanecMan** [comment]
> -На время убрать Анклав (иск. Ивенты)
Анклав и так редкосные дебилы, нахуя их выпиливать и ради какого ивента? 

> -Добавить наушник для НКР
Наушники не работают так как нет телекомов (добавлю) 

>-Увеличить количество обойм на М1 на базе НКР
Ок

>-Сделать нормальную базу НКР
Не видел её, гляну что с ней не так

>-Добавить в память имена всех бойцов
НКР, дабы понимать: Один ты или нет.
Шок коммунизм развивает телепатия теперь ты можешь знать имена своих товарищей (нет)

>-Я был-бы рад погонам капрала (Е-4) у обычной пехоты
Подробнее

>Это всё.

**Comment by Sarov991** [comment]
-На анклаве как раз играют идиоты, вместо обычных путников

-Сделай пажожда

-Спс

-Там обрубок, который больше похож на КПП, а не на базу

-Это не телепатия, а РП. По РП же проинформировать могут кто в пустоши? Могут

-В карман можно сложить погоны Е-3, а я хочу ещё Е-4
