### ISSUE TITLE
[ФИЧА] Повышение резистов и переноска пушек костюму исследователя.

### ISSUE THREAD

**Issue by Stalkeros2** [iWuna/Fallout-13-NewDecade#16]
Поднять резисты против пуль и лазеров до уровня ~~баллистического~~ обычного бронежилета, добавить возможность переноски в слоте костюма чего-нибудь помимо шахтёрского оборудования, т.е. огнестрельного оружия/лазеров/плазмы/*вставить пушечка_нейм*.
Увеличить количество 'разрешённых' переносимых предметов в разгрузке исследователя, чтобы носить в ней хотя бы магазины и стимуляторы.

**Comment by Stalkeros2** [comment]
Автор идиот и забыл настроить тэги.

**Comment by iWuna** [comment]
Будет рассмотрено в ближайшие сутки.

**Comment by Stalkeros2** [comment]
![image](https://user-images.githubusercontent.com/42087567/74448907-91baec80-4e9d-11ea-94be-e96a23e72f0c.png)
