### ISSUE TITLE
[БАГ] Бандана прайма. 

### ISSUE THREAD

**Issue by Major0911** [iWuna/Fallout-13-NewDecade#23]
**Опишите баг**
Бандану можно надеть так, что вместо её изображения на персонаже появляется надпись "ERROR".

**Как воспроизвести**
Как получить этот баг?
1. чтобы получить этот баг, нужно взять бандану, и вывернуть её для слота головы. 1. 
2. в руках вместо банданы появится надпись "ERROR". 
3. надев это на голову, на персонаже будет надпись "ERROR"
4. 

**Скриншоты**
Если есть

**Критичность бага**
имеет только визуальный эффект

**Comment by iWuna** [comment]
Исправил описание. Баг исправлен
