### ISSUE TITLE
[БАГ] Пачка сЫгарет весит 2.5 кг.

### ISSUE THREAD

**Issue by Oceket** [iWuna/Fallout-13-NewDecade#24]
**Опишите баг**
Да блять я курить хочу понимаешь самокруточку робуст голд сигарету хочю с капсулой золотой дождь робуст голд

**Как воспроизвести**
Как получить этот баг?
1. Находим винстон синий и.т.д
2. берём пачку в ручки
3. курим, пихаем в инвентарь
4. ???
5. Сука мы не можем бежать!!!

**Скриншоты**

![Говна_пирога](https://user-images.githubusercontent.com/38756693/78424925-77211a80-7679-11ea-8d38-db6e2a69b364.png)

**Критичность бага**
Для любителей отыгрывать куряг - это удар ниже пояса, остальным соболезную.

**Comment by iWuna** [comment]
Брух. Чекаю.

**Comment by iWuna** [comment]
Пофикшено.
